"""Generate or install project-scoped configuration for Codex MCP + GPT-5.6 Sol."""
from __future__ import annotations

import argparse
import json
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARKER = "# Generated by unreal_gpt/scripts/configure_codex.py"


def make_config(editor_python: str = "", python_executable: str = "",
                conda_exe: str = "", conda_prefix: str = "") -> str:
    quote = lambda path: json.dumps(str(path).replace("\\", "/"))
    executable = Path(python_executable).resolve() if python_executable else ROOT / ".venv/Scripts/python.exe"
    command = str(executable)
    arguments = [str(ROOT / "unreal_fable/mcp/codex_mcp.py")]
    if bool(conda_exe) != bool(conda_prefix):
        raise ValueError("Both --conda-exe and --conda-prefix are required for conda.")
    if conda_exe:
        command = str(Path(conda_exe).resolve())
        arguments = ["run", "--no-capture-output", "--prefix", str(Path(conda_prefix).resolve()),
                     str(executable), "-u", *arguments]
    text = f'''{MARKER}
model = "gpt-5.6-sol"
model_reasoning_effort = "medium"

[mcp_servers.codex_mcp]
command = {quote(command)}
args = [{', '.join(quote(arg) for arg in arguments)}]
cwd = {quote(ROOT)}
startup_timeout_sec = 30
tool_timeout_sec = 660
enabled = true

[mcp_servers.codex_mcp.env]
FABLE_DEVKIT = {quote(ROOT / "unreal_fable")}
UE_REMOTE_CONTROL = "http://127.0.0.1:30010"
FABLE_BRIDGE_PORT = "9800"
PYTHONUTF8 = "1"
'''
    if editor_python:
        text += f"UE_PROJECT_PYTHON = {quote(Path(editor_python).resolve())}\n"
    if conda_exe:
        # Windows conda activation uses TMP; MCP clients may only inherit TEMP.
        temp_dir = Path(tempfile.gettempdir()).resolve()
        text += f"TMP = {quote(temp_dir)}\nTEMP = {quote(temp_dir)}\n"
    tomllib.loads(text)
    return text


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install", action="store_true", help="Write .codex/config.toml in this project")
    parser.add_argument("--editor-python", default="", help="Unreal project's Content/Python directory")
    parser.add_argument("--python", default="", dest="python_executable", help="Python executable for the server")
    parser.add_argument("--conda-exe", default="", help="Conda executable to activate the server environment")
    parser.add_argument("--conda-prefix", default="", help="Absolute path of the conda environment")
    args = parser.parse_args()
    text = make_config(args.editor_python, args.python_executable, args.conda_exe, args.conda_prefix)
    target = ROOT / (".codex/config.toml" if args.install else "codex-config.toml")
    if target.exists() and not target.read_text(encoding="utf-8").startswith(MARKER):
        raise SystemExit(f"Existing configuration is not generated by this tool: {target}. Merge codex-config.toml manually.")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    print(target)
